#!/bin/bash

: <<'TetrisDoc'
    @Param      bool    1
        True if script is to be run in debug mode
TetrisDoc

extrap()
{
    stty sane <&6
    tput cvvis
    tput sgr0
    printf '\e[25;1H'
    exec 0<&6 6<&-
}
trap extrap EXIT

log()
{
    printf '\n%s:' "$*" 1>&2
}

logDir=/var/games/tetris
# Debug mode sends STDERR to an error file
export PS4='+(${LINENO}) ${FUNCNAME[0]}(): '
_debug=${1:-false}

if $_debug; then
    exec 2>~/debug.log
    set -xT
else
    exec 2>$logDir/error.log
fi

exec 6<&0 0</dev/null

stty -echo <&6  # Disable echo
tput civis  # Disable cursor blinker

hsLog="$logDir/highscores.ths"
touch "$hsLog" # Create score log if doesn't exist
libDir="/usr/local/lib/tetris"

# Import the assets
assetPath='Assets/'

_state=0
_level=0
_score=0
_lines=0
_currentPiece=
_nextPiece=
_rotation=
_pieceX=
_pieceY=
_inTTY=
_colourMode=

# Collision detection
declare -A _lock

if test -s "$settingsLog"; then
    :
else
    # If game is loaded on a terminal outside of a GUI environment
    if test -z "$DISPLAY" || [[ "$TERM" == "linux" ]]; then
        _inTTY=true
        _colourMode='SIMPLE'
    else
        _inTTY=false
        _colourMode='NORMAL'
    fi
fi

for asset in ${assetPath}*; do
    source "$asset"
done

movePiece()
{
    local               \
        nextX=$_pieceX  \
        nextY=$_pieceY

    case $direction in
        'D')    timeTaken=0 # Reset timer
                (( nextY++ ));;
        'R')    (( nextX += 2 ));;
        'L')    (( nextX -= 2 ));;
    esac

    canRender "$_currentPiece" $nextY $nextX

    if (( $collides == 0 )); then
        removePiece "$_currentPiece" $_pieceY $_pieceX
        renderPiece "$_currentPiece" $nextY $nextX
        _pieceX=$nextX
        _pieceY=$nextY
    elif [[ "$direction" == 'D' ]]; then
        lockPiece "$_currentPiece" $_pieceY $_pieceX
        newPiece=true
    fi
}

rotatePiece()
{
    local                           \
        captureRotation=$_rotation  \
        posX=$_pieceX               \
        posY=$_pieceY

    removePiece "$_currentPiece" $_pieceY $_pieceX

    (( _rotation == 3 ? _rotation = 0 : _rotation++ ))

    while ! canRender "$_currentPiece" $posY $posX; do
        case $collides in
            1)      (( posX -= 2 ));; # Right wall
            3)      (( posX += 2 ));; # Left wall
            2|4)    _rotation=$captureRotation
                    renderPiece "$_currentPiece" $_pieceY $_pieceX
                    return;; # Floor or another tetromino
        esac
    done

    _pieceX=$posX
    _pieceY=$posY

    renderPiece "$_currentPiece" $_pieceY $_pieceX
}

setDefaults()
{
    test -n "$_nextPiece" && _currentPiece=$_nextPiece || _currentPiece=${pieces[$(( $RANDOM % ${#pieces[@]} ))]}
    _nextPiece=${pieces[$(( $RANDOM % ${#pieces[@]} ))]}

    # Starting geometry for new pieces
    _rotation=0
    IFS=',' read _pieceY _pieceX <<< $startPosition
    newPiece=false
}

gameLoop()
{
    local                       \
        collides=0              \
        direction               \
        key1                    \
        key2                    \
        key3                    \
        updatePosition=false    \
        newPiece=true           \
        postTime                \
        preTime                 \
        readPid                 \
        speed                   \
        tick                    \
        timeTaken=0

    while true; do
        if $newPiece; then
            setDefaults
            canRender "$_currentPiece" $_pieceY $_pieceX
            (( $collides )) && : # Game Over
            renderPiece "$_currentPiece" $_pieceY $_pieceX
            renderNextPiece
            read -n10000 -t0.0001 <&6 # Clear input buffer
        elif $updatePosition; then
            # $_debug && log "move"
            movePiece
            updatePosition=false
            $newPiece && continue
        fi

        preTime=$( date '+%2N' )
        preTime=${preTime#0}

        # Lower numer means faster speed
        (( speed = 90 - $_level * 4 ))
        (( $speed < 20 )) && speed=20

        (( tick = $speed - $timeTaken ))
        (( $tick < 0 )) && tick=0
        (( $tick < 10 )) && tick="0$tick"

        # Read STDIN with the timeout relative to the speed
        IFS= read -rsn1 -t0.$tick key1 <&6
        readPid=$?
        IFS= read -rsn1 -t0.0001 key2 <&6
        IFS= read -rsn1 -t0.0001 key3 <&6

        # If read timeout was interrupted
        if (( $readPid != 142 )); then
            # If enter or space is pressed
            if test -z "$key1" || [[ "$key1" == " " ]]; then
                # $_debug && log "rotate"
                rotatePiece
            # If escape character is pressed
            elif [[ "$key1" == $'\e' ]]; then
                if test -z "$key2"; then
                    pause
                else
                    updatePosition=true
                    case $key3 in
                        B)  direction='D';; # Down
                        C)  direction='R';; # Right
                        D)  direction='L';; # Left
                    esac
                fi
            fi
        fi

        postTime=$( date '+%2N' )
        postTime=${postTime#0}

        (( $postTime < $preTime )) && (( postTime += 100 ))
        if (( $timeTaken )); then
            (( timeTaken += $postTime - $preTime ))
        else
            (( timeTaken = $postTime - $preTime ))
        fi

        if (( $timeTaken >= $speed )); then
            updatePosition=true
            direction='D'
            timeTaken=0
        fi
        unset key1 key2 key3
    done
}

# Set blank global variables to allow restarting
newGame()
{
    _level=0
    _score=0
    eval _lock[{2..23},{2..20..2}]=${coloursLookup[R]}

    # scoreModifier false
    gameLoop
    return $?
}

while true; do
    case $_state in
        *)  renderScreen;;&
        1)  newGame;;
    esac
done
